apiVersion: v1
kind: Service
metadata:
  name: analytics-api-service
  namespace: edu-app
spec:
  selector:
    app: analytics-api-service
  ports:
  - port: 80
    targetPort: 5005
  type: ClusterIP
